ProjectNghiPhep/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MVCGrid.Models;
using MVCGrid.Web;
using ProjectNghiPhep.Models;
using ProjectNghiPhep.Models.ViewModels;

namespace ProjectNghiPhep.Controllers
{
    public class NguoiDungController : Controller
    {
        //
        // GET: /DonNghiPhep/
           
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(string id)
        {
            var result = new QueryResult<User>();
            NghiphepEntities db = new NghiphepEntities();
            // Query your data here. Obey Ordering, paging and filtering parameters given in the context.QueryOptions.
            // Use Entity Framework, a module from your IoC Container, or any other method.
            // Return QueryResult object containing IEnumerable<YouModelItem>
            var query = (from user in db.Users
                         join contract in db.ContractTypes
                         on user.contractId equals contract.C_id
                         where user.C_id == id
                         select new
                         {
                             C_id = user.C_id,
                             departmentId = user.departmentId,
                             titleId = user.titleId,
                             username = user.username,
                             dayOff = user.dayOff,
                             contractId = user.contractId,
                             createdAt = user.createdAt,
                             ContractType = contract,
                             fullName = user.fullName,
                             email = user.email,
                             mobile = user.mobile
                         });
            var user_result = query.ToList().Select(r => new User
            {
                C_id = r.C_id,
                username = r.username,
                fullName = r.fullName,
                dayOff = r.dayOff,
                createdAt = r.createdAt,
                contractId = r.ContractType.C_id,
                departmentId = r.departmentId,
                titleId = r.titleId,
                ContractType = r.ContractType,
                email = r.email,
                mobile = r.mobile
            }).ToList()[0];

            var contract_query = (from contract in db.ContractTypes
                         select new
                         {
                             C_id = contract.C_id,
                             code = contract.code,
                             name = contract.name,
                             dayOff = contract.dayOff
                         });
            var contracts = contract_query.ToList().Select(c => new ContractType
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name,
                dayOff = c.dayOff
            }).ToList();
            var department_query = (from department in db.Departments
                                  select new
                                  {
                                      C_id = department.C_id,
                                      code = department.code,
                                      name = department.name
                                  });
            var departments = department_query.ToList().Select(c => new Department
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name
            }).ToList();
            var titles_query = (from contract in db.Titles
                                select new
                                {
                                    C_id = contract.C_id,
                                    code = contract.code,
                                    name = contract.name
                                });
            var titles = titles_query.ToList().Select(c => new Title
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name,
            }).ToList();
            ViewData["contracts"] = contracts;
            ViewData["departments"] = departments;
            ViewData["titles"] = titles;
            return View(user_result);
        }

        public ActionResult Profile(string id)
        {
            var result = new QueryResult<User>();
            NghiphepEntities db = new NghiphepEntities();
            // Query your data here. Obey Ordering, paging and filtering parameters given in the context.QueryOptions.
            // Use Entity Framework, a module from your IoC Container, or any other method.
            // Return QueryResult object containing IEnumerable<YouModelItem>
            var query = (from user in db.Users
                         join contract in db.ContractTypes
                         on user.contractId equals contract.C_id
                         where user.C_id == id
                         select new
                         {
                             C_id = user.C_id,
                             username = user.username,
                             dayOff = user.dayOff,
                             contractId = user.contractId,
                             departmentId = user.departmentId,
                             titleId = user.titleId,
                             createdAt = user.createdAt,
                             ContractType = contract,
                             fullName = user.fullName,
                             email = user.email,
                             mobile = user.mobile
                         });
            var user_result = query.ToList().Select(r => new User
            {
                C_id = r.C_id,
                username = r.username,
                fullName = r.fullName,
                dayOff = r.dayOff,
                createdAt = r.createdAt,
                contractId = r.contractId,
                departmentId = r.departmentId,
                titleId = r.titleId,
                ContractType = r.ContractType,
                email = r.email,
                mobile = r.mobile
            }).ToList()[0];

            var contract_query = (from contract in db.ContractTypes
                                  select new
                                  {
                                      C_id = contract.C_id,
                                      code = contract.code,
                                      name = contract.name,
                                      dayOff = contract.dayOff
                                  });
            var contracts = contract_query.ToList().Select(c => new ContractType
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name,
                dayOff = c.dayOff
            }).ToList();
            var department_query = (from department in db.Departments
                                    select new
                                    {
                                        C_id = department.C_id,
                                        code = department.code,
                                        name = department.name
                                    });
            var departments = department_query.ToList().Select(c => new Department
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name
            }).ToList();
            var titles_query = (from contract in db.Titles
                                select new
                                {
                                    C_id = contract.C_id,
                                    code = contract.code,
                                    name = contract.name
                                });
            var titles = titles_query.ToList().Select(c => new Title
            {
                C_id = c.C_id,
                code = c.code,
                name = c.name,
            }).ToList();
            ViewData["contracts"] = contracts;
            ViewData["departments"] = departments;
            ViewData["titles"] = titles;
            return View(user_result);
        }

        public ActionResult DeleteUser(string id)
        {
            NghiphepEntities db = new NghiphepEntities();
            var result = db.Users.SingleOrDefault(b => b.C_id == id);
            if (result != null)
            {
                result.isActive = false;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult SaveUser (User user)
        {
            NghiphepEntities db = new NghiphepEntities();
            var result = db.Users.SingleOrDefault(b => b.username == user.username);
            if (result != null)
            {
                result.username = user.username;
                result.fullName = user.fullName;
                result.email = user.email;
                result.mobile = user.mobile;
                result.departmentId = user.departmentId;
                result.titleId = user.titleId;
                result.contractId = user.contractId;
                //result.contractId = user.contractId;
                result.dayOff = user.dayOff;
                db.SaveChanges();
            }
            return RedirectToAction("Edit/" + result.C_id);
        }

        //Gọi form thêm người dùng
        public ActionResult CreateUser()
        {
            NghiphepEntities db = new NghiphepEntities();
            var contract_query = (from contract in db.ContractTypes
                                  select new
                                  {
                                      C_id = contract.C_id,
                                      code = contract.code,
                                      name = contract.name,
                                      dayOff = contract.dayOff
                                  });

ProjectNghiPhep/Views/NguoiDung/ChangePassword.cshtml
@model ProjectNghiPhep.Models.ViewModels.ChangePasswordViewModel

@{
                /**/

                ViewBag.Title = "ChangePassword";
                Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Vieu đổi mật khau*@
<h2>Đổi mật khẩu</h2>
@using (Html.BeginForm("ChangePassword", "NguoiDung", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />

    if (!string.IsNullOrEmpty(@ViewBag.MessageSuccess))
    {
        <div class="text-success">
            @ViewBag.MessageSuccess
        </div>
    }
    else
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CurrentPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                <br />
                @Html.ValidationMessageFor(m => m.CurrentPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                <br />
                @Html.ValidationMessageFor(m => m.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewPasswordAgain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.NewPasswordAgain, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                <br />
                @Html.ValidationMessageFor(m => m.NewPasswordAgain, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    }
}

ProjectNghiPhep/Views/NguoiDung/CreateNew.cshtml
@model ProjectNghiPhep.Models.User
@{
    ViewBag.Title = "CreateNew";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateUser", "NguoiDung", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Cập nhật thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.username, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.email, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contractId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="height: 27px;">
                <select class="form-control" name="test" style="width: 300px;">
                    @foreach (var item in ViewBag.contracts)
                    {
                        <option value="@item.C_id">@item.name</option>
                    }
                </select>
                <br />
                @Html.ValidationMessageFor(model => model.contractId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dayOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.dayOff, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.dayOff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ProjectNghiPhep/Views/NguoiDung/CreateUser.cshtml
@model ProjectNghiPhep.Models.NHANVIEN
@{
    ViewBag.Title = "CreateNew";
}

<section id="loginForm">
    @using (Html.BeginForm("CreateUserForm", "NguoiDung", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-horizontal">
            <h4>Đăng ký</h4>
            <hr />
            <div class="form-group">
                @Html.LabelFor(m => m.username, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.username)
                    @Html.ValidationMessageFor(m => m.username)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.fullName, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.fullName)
                    @Html.ValidationMessageFor(m => m.fullName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.password, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.PasswordFor(m => m.password)
                    @Html.ValidationMessageFor(m => m.password)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.contractId, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.contractId, new SelectList(ViewBag.contracts, "C_id", "name"), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.contractId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.titleId, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.titleId, new SelectList(ViewBag.titles, "C_id", "name"), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.titleId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.departmentId, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.departmentId, new SelectList(ViewBag.departments, "C_id", "name"), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.departmentId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.email, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.email)
                    @Html.ValidationMessageFor(m => m.email)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.gender, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.gender)
                    @Html.ValidationMessageFor(m => m.gender)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.address, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.address)
                    @Html.ValidationMessageFor(m => m.address)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.mobile, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(m => m.mobile)
                    @Html.ValidationMessageFor(m => m.mobile)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <input type="submit" value="Lưu" />
                </div>
            </div>
        </div>
    }
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectNghiPhep/Views/NguoiDung/Edit.cshtml
@model ProjectNghiPhep.Models.User
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("SaveUser", "NguoiDung", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @*<script>
        $(document).ready(function ready() {
            setTimeout(function () {
                $("#contracts").val(@Model.contractId)
                $("#titles").val(@Model.titleId)
                $("#departments").val(@Model.departmentId)
            }, 500)
        })
    </script>*@
    <div class="form-horizontal">
        <h4>Cập nhật thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.username, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contractId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.contractId, new SelectList(ViewBag.contracts, "C_id", "name", @Model.contractId), htmlAttributes: new { @class = "form-control", @id="contracts" })
                @Html.ValidationMessageFor(model => model.contractId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.titleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.titleId, new SelectList(ViewBag.titles, "C_id", "name", @Model.titleId), htmlAttributes: new { @class = "form-control", @id = "titles" })
                @Html.ValidationMessageFor(model => model.titleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.departmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.departmentId, new SelectList(ViewBag.departments, "C_id", "name", @Model.departmentId), htmlAttributes: new { @class = "form-control", @id = "departments" })
                @Html.ValidationMessageFor(model => model.departmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dayOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.dayOff, new { htmlAttributes = new { @class = "form-control" }, type = "number" })
                <br />
                @Html.ValidationMessageFor(m => m.dayOff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ProjectNghiPhep/Views/NguoiDung/Index.cshtml
@using MVCGrid.Web
@{
    ViewBag.Title = "DonNghiPhep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page_header">
    <h2>Nhân viên</h2>
    <button class="btn-primary">
        @Html.ActionLink("Tạo mới", "CreateUser", "NguoiDung")
    </button>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @Html.MVCGrid("UserGrid")
    </div>
</div>

ProjectNghiPhep/Views/NguoiDung/Profile.cshtml
@model ProjectNghiPhep.Models.User
@{
    ViewBag.Title = "CreateNew";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("SaveUser", "NguoiDung", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Cập nhật thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.username, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly" })
                <br />
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contractId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.contractId, new SelectList(ViewBag.contracts, "C_id", "name", @Model.contractId), htmlAttributes: new { @class = "form-control profile-disable" })
                @Html.ValidationMessageFor(model => model.contractId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.titleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.titleId, new SelectList(ViewBag.titles, "C_id", "name", @Model.titleId), htmlAttributes: new { @class = "form-control profile-disable" })
                @Html.ValidationMessageFor(model => model.titleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.departmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.departmentId, new SelectList(ViewBag.departments, "C_id", "name", @Model.departmentId), htmlAttributes: new { @class = "form-control profile-disable" })
                @Html.ValidationMessageFor(model => model.departmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dayOff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.dayOff, new { htmlAttributes = new { @class = "form-control" }, type = "number" })
                <br />
                @Html.ValidationMessageFor(m => m.dayOff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
    
    <button class="btn-primary">
        @Html.ActionLink("Đổi mật khẩu", "ChangePassword", "NguoiDung")
    </button>
}