PJNghiPhep-master/ProjectNghiPhep/Controllers/DonNghiPhepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectNghiPhep.Models;

namespace ProjectNghiPhep.Controllers
{
    public class DonNghiPhepController : Controller
    {
        //
        // GET: /DonNghiPhep/
           
        public ActionResult Manager(string id)
        {
            if (id != null)
            {
                NghiphepEntities db = new NghiphepEntities();
                var query = (from user in db.Users
                             join title in db.Titles
                             on user.titleId equals title.C_id
                             where user.C_id == id
                             select new
                             {
                                 C_id = user.C_id,
                                 title = title,
                                 username = user.username
                             });
                var users = query.ToList().Select(r => new User
                {
                    C_id = r.C_id,
                    Title = r.title,
                    username = r.username
                }).ToList();
                return View(users[0]);
            }
            else
            {
                return View(new User() {
                    username = "default",
                    Title = new Title()
                    {
                        name = "Default"
                    }
                });
            }
        }

        public ActionResult Employee(string id)
        {
            if (id != null)
            {
                NghiphepEntities db = new NghiphepEntities();
                var query = (from user in db.Users
                             join title in db.Titles
                             on user.titleId equals title.C_id
                             where user.C_id == id
                             select new
                             {
                                 C_id = user.C_id,
                                 title = title,
                                 username = user.username
                             });
                var users = query.ToList().Select(r => new User
                {
                    C_id = r.C_id,
                    Title = r.title,
                    username = r.username
                }).ToList();
                return View(users[0]);
            }
            else
            {
                return View(new User()
                {
                    username = "default",
                    Title = new Title()
                    {
                        name = "Default"
                    }
                });
            }
        }

        public ActionResult CreateNew()
        {
            return View();
        }

        private string CreateAutoCode(string currentCode)
        {
            if (currentCode != null)
            {
                string resultString = "";
                string numberString = currentCode.Split('_')[1];
                int number = Int32.Parse(numberString) + 1;
                resultString = number.ToString();
                while(resultString.Length < 6) {
                    resultString = "0" + resultString;
                }
                return "NP_" + resultString;
            } else {
                return "NP_000001";
            }
        }

        [HttpPost]
        public ActionResult CreateLeaveForm(TaoDonNghiPhep dnp)
        {
            System.Diagnostics.Debug.WriteLine("CreateLeaveForm CreateLeaveForm CreateLeaveForm");
            if (ModelState.IsValid)
            {
                NghiphepEntities db = new NghiphepEntities();
                Document document = queryDocument();
                string code = CreateAutoCode(document.code);
                db.Documents.Add(new Document()
                {
                    C_id = code,
                    code = code,
                    status = 0,
                    createdAt = (float)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds * 1000,
                    startDate = (float)(DateTime.ParseExact(dnp.dateStart, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture).Subtract(new DateTime(1970, 1, 1))).TotalSeconds * 1000,
                    endDate = (float)(DateTime.ParseExact(dnp.dateEnd, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture).Subtract(new DateTime(1970, 1, 1))).TotalSeconds * 1000,
                    createdById = "USER_002"
                });
                db.SaveChanges();
                //write code to update student 
                return RedirectToAction("Index");
            }
            return RedirectToAction("CreateNew");
        }

        private Document queryDocument()
        {
            NghiphepEntities db = new NghiphepEntities();
            var query = (from doc in db.Documents
                         join user in db.Users
                         on doc.createdById equals user.C_id
                         select new
                         {
                             C_id = doc.C_id,
                             createdBy = user,
                             code = doc.code,
                             status = doc.status,
                             createdAt = doc.createdAt
                         }).OrderBy(x => x.code);
            var documents = query.ToList().Select(r => new Document
            {
                C_id = r.C_id,
                createdBy = r.createdBy,
                code = r.code,
                status = r.status,
                createdAt = r.createdAt
            }).ToList();
            documents.Reverse();
            return documents[0];
        }

        [HttpGet]
        public ActionResult VerifyDocument(string id)
        {
            NghiphepEntities db = new NghiphepEntities();
            Document document = queryDocument();
            var result = db.Documents.SingleOrDefault(b => b.C_id == id);
            if (result != null)
            {
                result.status = 99;
                db.SaveChanges();
            }
            var user = db.Users.SingleOrDefault(b => b.C_id == result.createdById);
            if (user != null)
            {
                user.dayOff = user.dayOff - (int)((result.endDate - result.startDate) / 1000 / 3600 / 24);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CancelDocument(string id)
        {
            NghiphepEntities db = new NghiphepEntities();
            Document document = queryDocument();
            var result = db.Documents.SingleOrDefault(b => b.C_id == id);
            if (result != null)
            {
                result.status = 100;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

PJNghiPhep-master/ProjectNghiPhep/Views/DonNghiPhep/CreateNew.cshtml
@model ProjectNghiPhep.Models.TaoDonNghiPhep
@{
    ViewBag.Title = "CreateNew";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CreateLeaveForm", "DonNghiPhep", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Tạo đơn nghỉ phép</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.dateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.dateStart, new { htmlAttributes = new { @class = "form-control" }, type="date" })
                <br />
                @Html.ValidationMessageFor(model => model.dateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.dateEnd, new { htmlAttributes = new { @class = "form-control" }, type="date" })
                <br />
                @Html.ValidationMessageFor(model => model.dateEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.reason, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.reason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PJNghiPhep-master/ProjectNghiPhep/Views/DonNghiPhep/Employee.cshtml
@model ProjectNghiPhep.Models.User
@using MVCGrid.Web
@{
    ViewBag.Title = "DonNghiPhep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page_header">
    <h2>Đơn Nghỉ Phép</h2>
    <button class="btn-primary">
        @Html.ActionLink("Tạo mới", "CreateNew", "DonNghiPhep")
    </button>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <script>
            function onChangeTab(tabName) {
                $('#waiting').removeClass('active');
                $('#verify').removeClass('active');
                $('#cancel').removeClass('active');
                $('#waitingTab').hide();
                $('#verifyTab').hide();
                $('#cancelTab').hide();
                $(tabName + 'Tab').show();
                $(tabName).addClass('active');
            }
            if (!window.localStorage.getItem('token')) {
                window.localStorage.setItem('title', '@Model.Title.code');
                window.localStorage.setItem('token', '@Model.C_id');
            } else {
                var title = window.localStorage.getItem('title')
                $('#waitingTab').hide()
                //if (title !== 'GIAMDOC') {
                //    setTimeout(function () {
                //        console.log($('.btn-verify'))
                //        $('.btn-verify').hide()
                //        $('.btn-cancel').hide()
                //    }, 5000)
                //}
            }
        </script>
        <ul class="nav nav-tabs">
            <li class="active" id="waiting"><a href="#" onclick="onChangeTab('#waiting')">Đơn chờ duyệt</a></li>
            <li id="verify"><a href="#" onclick="onChangeTab('#verify')">Đơn đã duyệt</a></li>
            <li id="cancel"><a href="#" onclick="onChangeTab('#cancel')">Đơn đã hủy</a></li>
        </ul>
        <div id="waitingTab">
            @Html.MVCGrid("WaitingDocumentGridEm")
        </div>
        <div id="verifyTab" style="display: none">
            @Html.MVCGrid("VerifyDocumentGridEm")
        </div>
        <div id="cancelTab" style="display: none">
            @Html.MVCGrid("CancelDocumentGridEm")
        </div>
    </div>
</div>

PJNghiPhep-master/ProjectNghiPhep/Views/DonNghiPhep/Manager.cshtml
@model ProjectNghiPhep.Models.User
@using MVCGrid.Web
@{
    ViewBag.Title = "DonNghiPhep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page_header">
    <h2>Đơn Nghỉ Phép</h2>
    <button class="btn-primary">
        @Html.ActionLink("Tạo mới", "CreateNew", "DonNghiPhep")
    </button>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <script>
            function onChangeTab(tabName) {
                $('#waiting').removeClass('active');
                $('#verify').removeClass('active');
                $('#cancel').removeClass('active');
                $('#waitingTab').hide();
                $('#verifyTab').hide();
                $('#cancelTab').hide();
                $(tabName + 'Tab').show();
                $(tabName).addClass('active');
            }
            if (!window.localStorage.getItem('token')) {
                window.localStorage.setItem('title', '@Model.Title.code');
                window.localStorage.setItem('token', '@Model.C_id');
            } else {
                var title = window.localStorage.getItem('title')
                $('#waitingTab').hide()
                //if (title !== 'GIAMDOC') {
                //    setTimeout(function () {
                //        console.log($('.btn-verify'))
                //        $('.btn-verify').hide()
                //        $('.btn-cancel').hide()
                //    }, 5000)
                //}
            }
        </script>
        <ul class="nav nav-tabs">
            <li class="active" id="waiting"><a href="#" onclick="onChangeTab('#waiting')">Đơn chờ duyệt</a></li>
            <li id="verify"><a href="#" onclick="onChangeTab('#verify')">Đơn đã duyệt</a></li>
            <li id="cancel"><a href="#" onclick="onChangeTab('#cancel')">Đơn đã hủy</a></li>
        </ul>
        <div id="waitingTab">
            @Html.MVCGrid("WaitingDocumentGrid")
        </div>
        <div id="verifyTab" style="display: none">
            @Html.MVCGrid("VerifyDocumentGrid")
        </div>
        <div id="cancelTab" style="display: none">
            @Html.MVCGrid("CancelDocumentGrid")
        </div>
    </div>
</div>