PJNghiPhep-master/ProjectNghiPhep/Controllers/PhanQuyensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using ProjectNghiPhep.Models;

namespace ProjectNghiPhep.Controllers
{
    public class PhanQuyensController : Controller
    {
        //
        // GET: /PhanQuyens/
        dataForPQ.dbpq dbPQ = new dataForPQ.dbpq();

        public ActionResult ShowDataBasePhanQuyen()
        {
            return View();
        }

        public JsonResult get_data() {
            DataSet ds = dbPQ.DataForPhanQuyen();
            List<ShowDataBaseForPhanQuyen> listPQ = new List<ShowDataBaseForPhanQuyen>();
            foreach (DataRow dr in ds.Tables[0].Rows){
                listPQ.Add(new ShowDataBaseForPhanQuyen
                {
                    MaNV = Convert.ToInt32(dr["MaNV"]),
                    TenNV = dr["TenNV"].ToString(),
                    Email = dr["Email"].ToString(),
                    chucvu = dr["chucvu"].ToString(),
                    user_name = dr["user_name"].ToString(),
                    id_per_rel = Convert.ToInt32(dr["id_per_rel"]),
                    name_per = dr["name_per"].ToString()
                });
            }
            return Json(listPQ, JsonRequestBehavior.AllowGet);
        }
	}
}

PJNghiPhep-master/ProjectNghiPhep/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MVCGrid.Models;
using MVCGrid.Web;
using ProjectNghiPhep.Models;

    

namespace ProjectNghiPhep.Controllers
{
    public class RegistersController : Controller
    {
        //SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["con"].ConnectionString);
        NghiphepEntities db = new NghiphepEntities();
        //
        // GET: /Registers/
        public ActionResult SetDataInDataBase()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SetDataInDataBase(User model)
        {
            User tbl = new User();
            tbl.C_id = model.C_id;
            tbl.fullName = model.fullName;
            tbl.gender = model.gender;
            //tbl.dateOfBirth = (float)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds * 1000;
            tbl.dateOfBirth = model.dateOfBirth;
            tbl.address = model.address;
            tbl.email = model.email;
            tbl.mobile = model.mobile;
            tbl.username = model.username;
            tbl.password = model.password;
            /////////////////////////Kiểm tra radiobutton///////////////
            if (model.titleId != null)
            {
                tbl.titleId = "TITLE_001";
            }
            else
            {
                tbl.titleId = "TITLE_002";
            }
            ///////////////////////////////////////////////////////////
            tbl.isActive = true;

            db.Users.Add(tbl);
            db.SaveChanges();
            return View();
        }


        public ActionResult ShowDataBaseForUser(string id)
        {
            //var item = db.Users.ToList();
            //return View(item);
            if (id != null)
            {
                NghiphepEntities db = new NghiphepEntities();
                var query = (from user in db.Users
                             select new
                             {
                                 C_id = user.C_id,
                                 isActive = user.isActive,
                                 titleId = user.titleId,
                                 username = user.username,
                                 fullName = user.fullName,
                                 address = user.address,
                                 gender = user.gender,
                                 email = user.email,
                                 mobile = user.mobile,

                             });
                var users = query.ToList().Select(r => new User
                {
                    C_id = r.C_id,
                    isActive = r.isActive,
                    titleId = r.titleId,
                    username = r.username,
                    fullName = r.fullName,
                    address = r.address,
                    gender = r.gender,
                    email = r.email,
                    mobile = r.mobile,
                }).ToList();
                return View(users[0]);
            }
            else
            {
                return View(new User()
                {
                    username = "default",
                    Title = new Title()
                    {
                        name = "Default"
                    }
                });
            }
        }

        public ActionResult Delete(string id)
        {
            var item = db.Users.Where(x => x.C_id == id).First();
            db.Users.Remove(item);
            db.SaveChanges();
            var item2 = db.Users.ToList();
            return View("ShowDataBaseForUser", item2);
        }

       
        public ActionResult Edit(string id)
        {
            var item = db.Users.Where(x => x.C_id == id).First();

            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(User modl)
        {
            var item = db.Users.Where(x => x.C_id == modl.C_id).First();
            item.C_id = modl.C_id;
            item.fullName = modl.fullName;
            item.gender = modl.gender;
            //item.dateOfBirth = (float)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds * 1000;
            item.dateOfBirth = modl.dateOfBirth;
            item.address = modl.address;
            item.email = modl.email;
            item.mobile = modl.mobile;
            item.username = modl.username;
            item.password = modl.password;

            db.SaveChanges();
            return View();
        }
       
        //[HttpPost]


        ////////////////////////////////
        //[HttpPost]
        //public ActionResult PhanQuyen(tbl_per_relationship model)
        //{
        //    tbl_per_relationship tbl2 = new tbl_per_relationship();
        //    tbl2.id_user_rel = model.id_user_rel;
        //    tbl2.id_per_rel = model.id_per_rel;

        //    db.tbl_per_relationship.Add(tbl2);
        //    db.SaveChanges();
        //    return View();
        //}
        
        //public ActionResult PhanQuyen()
        //{
        //   
        //    return View();
        //}

        //public ActionResult ShowDataBaseForPhanQuyen()
        //{
        //    SqlCommand cmd = new SqlCommand("SELECT [MaNV],[TenNV],[Email] ,[chucvu],[user_name],[id_per_rel],[name_per] FROM [dbo].[NHANVIEN] NV INNER JOIN [dbo].[tbl_per_relationship] RL ON NV.MaNV = RL.id_user_rel INNER JOIN [dbo].[tbl_permision] PM ON RL.id_per_rel = PM.id_per WHERE NV.MaNV = RL.id_user_rel", con);

        //    return View();
        //}
        //[HttpPost]
        //public ActionResult VerifyUser(User id)
        //{
        //    NghiphepEntities db = new NghiphepEntities();
        //    var item = db.Users.Where(x => x.C_id == modl.C_id).First();
        //    var result = db.Users.Where(b => b.C_id == id.C_id).First();
        //    if (result != null)
        //    {
        //        result.isActive = true;
        //        db.SaveChanges();
        //    }
        //    return View();
        //    return RedirectToAction("Index");
        //}

        //private User queryUser()
        //{
        //    NghiphepEntities db = new NghiphepEntities();
        //    var query = (from user in db.Users
        //                 join tit in db.Titles
        //                 on user.titleId equals tit.C_id
        //                 select new
        //                 {
        //                     titleId = user.C_id
        //                     //C_id = user.C_id,
        //                     //createdBy = user,
        //                     //code = doc.code,
        //                     //status = doc.status,
        //                     //createdAt = doc.createdAt
        //                 }).OrderBy(x => x.titleId);
        //    var users = query.ToList().Select(r => new User
        //    {
        //        titleId = r.titleId
        //    }).ToList();
        //    users.Reverse();
        //    return users[0];
        //}
	}
}

PJNghiPhep-master/ProjectNghiPhep/Views/Registers/Edit.cshtml
@model ProjectNghiPhep.Models.User
           
           @using (Html.BeginForm())
           {
              <div class="container">
                  <div class="form-group">
                      <label>Mã nhân viên</label>
                      @Html.TextBoxFor(x => x.C_id, new { @class = "form-control" })
                  </div> 
                  <div class="form-group">
                      <label>Họ & tên</label>
                      @Html.TextBoxFor(x => x.fullName, new { @class = "form-control" })
                  </div> 
                  <div class="form-group">
                      <label>User name</label>
                      @Html.TextBoxFor(x => x.username, new { @class = "form-control" })
                  </div> 
                  <div class="form-group">
                      <label>Mật khẩu</label>
                      @Html.TextBoxFor(x => x.password, new { @class = "form-control" })
                  </div> 
                  <div class="form-group">
                      <label>Ngày sinh</label>
                      @Html.TextBoxFor(x => x.dateOfBirth, new { @class = "form-control" })
                  </div>
                  <div class="form-group">
                      <label>Giới tính</label>
                      @Html.TextBoxFor(x => x.gender, new { @class = "form-control" })
                  </div>
                  <div class="form-group">
                      <label>Số điện thoại</label>
                      @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" })
                  </div>
                  <div class="form-group">
                      <label>Email</label>
                      @Html.TextBoxFor(x => x.email, new { @class = "form-control" })
                  </div>
                  <div class="form-group">
                      <label>Địa chỉ</label>
                      @Html.TextBoxFor(x => x.address, new { @class = "form-control" })
                  </div>

                  @*<div class="form-group">
                      <input type="checkbox" id="1" />
                      <label>Ban chủ nhiệm khoa</label>  
                  </div>
                  <div class="form-group">
                      <input type="checkbox" id="2" />
                      <label>Quản trị viên</label>
                 </div>
                  <div class="form-group">
                      <input type="checkbox" id="3" />
                      <label>Nhân viên</label>
                  </div>*@
                  <div class="form-group">
                      <label>Phân quyền</label>
                    <i class="glyphicon glyphicon-edit">
                        @Html.ActionLink("Phân quyền", "PhanQuyen", "Registers")
                    </i>
                  </div>

                  

                  <div class="button">
                      <button>Lưu</button>
                  </div>
              </div> 
           }

PJNghiPhep-master/ProjectNghiPhep/Views/Registers/PhanQuyen.cshtml
@model ProjectNghiPhep.Models.tbl_per_relationship
@*@model List<demo16.Models.NHANVIEN>*@
@using (Html.BeginForm())
{
    <div class="container">
        <div class="form-group">
            <label>Mã nhân viên:</label>
            <input class="form-control" name="id_user_rel" placeholder="Enter id_per_rel" />
        </div>
        <div class="form-group">
            <label>Mã phân quyền</label>
            <input class="form-control" name="id_per_rel" placeholder="Enter id_per_rel" />
        </div>
        <div class="button">
            <button>
                Lưu
            </button>
        </div>
    </div>

    ///////////////////////////////////////////////////////
    @*<div class="container">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Họ & tên</th>
                    <th>Giới tính</th>
                    <th>Ngày sinh</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Email</th>
                    <th>Chức vụ</th>
                    <th>User id</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td>@Model[i].MaNV</td>
                        <td>@Model[i].TenNV</td>
                        <td>@Model[i].GioiTinh</td>
                        <td>@Model[i].NgaySinh</td>
                        <td>@Model[i].DiaChi</td>
                        <td>@Model[i].SDT</td>
                        <td>@Model[i].Email</td>
                        <td>@Model[i].chucvu</td>
                        <td>@Model[i].id_user</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>*@
    ///////////////////////////////////////////////////////
}

PJNghiPhep-master/ProjectNghiPhep/Views/Registers/SetDataInDatabase.cshtml
@model ProjectNghiPhep.Models.User

<section>
    @using (Html.BeginForm("SetDataInDatabase", "Registers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-horizontal">
            <h4>Thêm người dùng mới</h4>
            <hr />
            <div class="form-group">
                <label class="control-label col-md-2">Mã nhân viên</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.C_id)
                    @Html.ValidationMessageFor(m => m.C_id)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Họ & tên</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.fullName)
                    @Html.ValidationMessageFor(m => m.fullName)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Giới tính</label>  
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.gender)
                    @Html.ValidationMessageFor(m => m.gender)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Ngày sinh</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.dateOfBirth, "{dd-MM-yyyy}")
                    @Html.ValidationMessageFor(m => m.dateOfBirth)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Địa chỉ</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.address)
                    @Html.ValidationMessageFor(m => m.address)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Email</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.email, new { @placeholder = "E-mail" })
                    @Html.ValidationMessageFor(m => m.email)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Số điện thoại</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.mobile)
                    @Html.ValidationMessageFor(m => m.mobile)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Tên đăng nhập</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.username)
                    @Html.ValidationMessageFor(m => m.username)
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Mật khẩu</label>
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.password)
                    @Html.ValidationMessageFor(m => m.password)
                </div>
            </div>
            <div>  
                <div class="form-group">
                    <label class="control-label col-md-2">Phân quyền</label>
                    <div class="col-md-2">
                        <div>
                            @Html.RadioButtonFor(m => m.titleId, "1", new { @class = "control-label col-md-2" })
                            @Html.Label("Quản trị")
                        </div>
                        <div>
                            @Html.RadioButtonFor(m => m.titleId, "", new { @class = "control-label col-md-2" })
                            @Html.Label("Nhân viên")
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="button">
                        <button>
                            Duyệt
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</section>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

PJNghiPhep-master/ProjectNghiPhep/Views/Registers/ShowDataBaseForUser.cshtml
@model ProjectNghiPhep.Models.User
@using MVCGrid.Web
@{
    ViewBag.Title = "QuanLyNguoiDung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page_header">
    <h2>Quản Lý Người Dùng</h2>
    <button class="btn-primary">
        @Html.ActionLink("Tạo mới", "SetDataInDatabase", "Registers")
    </button>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <script>
            function onChangeTab(tabName) {
                $('#waiting').removeClass('active');
                $('#verify').removeClass('active');
                $('#nguoidung').removeClass('active');
                $('#waitingTab').hide();
                $('#verifyTab').hide();
                $('#nguoidungTab').hide();
                $(tabName + 'Tab').show();
                $(tabName).addClass('active');
            }
            if (!window.localStorage.getItem('token')) {
                window.localStorage.setItem('title', '@Model.Title.code');
                window.localStorage.setItem('token', '@Model.C_id');
            } else {
                var title = window.localStorage.getItem('title')
                $('#waitingTab').hide()
                //if (title !== 'GIAMDOC') {
                //    setTimeout(function () {
                //        console.log($('.btn-verify'))
                //        $('.btn-verify').hide()
                //        $('.btn-cancel').hide()
                //    }, 5000)
                //}
            }
        </script>
        <ul class="nav nav-tabs">
            <li class="active" id="waiting"><a href="#" onclick="onChangeTab('#waiting')">Người dùng chờ duyệt</a></li>
            <li id="verify"><a href="#" onclick="onChangeTab('#verify')">Người dùng đã duyệt</a></li>
            <li id="nguoidung"><a href="#" onclick="onChangeTab('#nguoidung')">Người dùng</a></li>    
        </ul>
        <div id="waitingTab">
            @Html.MVCGrid("WaitingUserGrid")
        </div>
        <div id="verifyTab" style="display: none">
            @Html.MVCGrid("VerifyUserGrid")
        </div>
        <div id="nguoidungTab" style="display: none">
            @Html.MVCGrid("VerifyUsersGrid")
        </div>
    </div>
</div>
@*<div class="modal" id="loginModal" style=" background-color: red">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">



            </div>
        </div>
    </div>
</div>*@

@*////////////////////////////////Nhấn nút VIEW////////////////////////////////*@
@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

</script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal").click(function () {
            $("#loginModal").modal('show');
        });

        $("#btnHideModal").click(function () {
            $("#loginModal").modal('hide');
        });
    });
</script>*@
 
@*///////////////////////////////////////////////////////////////*@
           @*<div class="container">
               <div class="form-group" title="Thêm mới">
                   <a href="@Url.Action("SetDataInDatabase")"><i class="glyphicon glyphicon-plus"></i></a>
               </div>
               <table class="table table-bordered">
                   <thead>
                       <tr>
                           <th>Mã nhân viên</th>
                           <th>Họ & tên</th>
                           <th>User name</th>
                           <th>Password</th>
                           <th>Giới tính</th>
                           <th>Ngày sinh</th>
                           <th>Email</th>
                           <th>Số điện thoại</th>
                           <th>Địa chỉ</th>
                           <th>Action</th>
                       </tr>
                   </thead>
                   <tbody>
                       @for (int i = 0; i < Model.Count(); i++)
                       {
                           <tr>
                               <td>@Model[i].C_id</td>
                               <td>@Model[i].fullName</td>
                               <td>@Model[i].username</td>
                               <td>@Model[i].password</td>
                               <td>@Model[i].gender</td>
                               <td>@Model[i].dateOfBirth</td>
                               <td>@Model[i].email</td>
                               <td>@Model[i].mobile</td>
                               <td>@Model[i].address</td>

                               <td>
                                   <a href="@Url.Action("Edit", new { id = Model[i].C_id })"><i class="glyphicon glyphicon-edit"></i></a>
                                   <a href="@Url.Action("Delete", new { id = Model[i].C_id })"><i class="glyphicon glyphicon-trash"></i></a>
                               </td>
                            </tr>
                       }
                   </tbody>
               </table>
           </div>*@